### ISSUE TITLE
Design / investigate separation of ROCrates by unique ID

### ISSUE THREAD

**Issue by douglowe** [eScienceLab/RO-Crate_Issues#14]
Avoid them all being `<file:///dev>` by making absolute URIs.

See https://www.researchobject.org/ro-crate/1.2-DRAFT/appendix/relative-uris.html#parsing-as-rdf-with-a-different-ro-crate-root on how to make absolute URIs and https://s11.no/2018/arcp.html on how to make these for an archive such as a ZIP file.

It may also be good to have separate `@graph` for each RO-Crate metadata file so they can be queried separate (e.g. they may each declare a `Person` but with a slightly different `name` attribute) -- see https://www.w3.org/TR/json-ld11/#named-graphs

**Comment by OliverWoolland** [comment]
This was solved using @base and arcp
