### ISSUE TITLE
Decide / investigate where to store ROCrates in Cratey

### ISSUE THREAD

**Issue by douglowe** [eScienceLab/RO-Crate_Issues#18]

**Comment by alexhambley** [comment]
Update: Plan is to use Minio for storage, but there is probably a more optimal way to store structured data for the JSON-LD portion of an RO Crate for querying, etc. Need to decide if this is worth the effort.

**Comment by alexhambley** [comment]
Done as we know RO Crates will stored in Minio data object. Now down to documentation architecture to further establish requirements
