### ISSUE TITLE
Generate metadata/provenance about the knowledge graph as a dataset

### ISSUE THREAD

**Issue by stain** [eScienceLab/RO-Crate_Issues#20]
Ideally in the Zenodo deposit of the knowledge graph there will also be metadata about the graph and how it was built. This can be an RO-Crate itself (which has the graph file as a data entity) with some provenance on its generation (e.g. from workflow). 

There are also more standard descriptors for RDF datasets using Void/DCAT https://www.w3.org/TR/void/ to count number of triples etc -- some basic queries over the dataset may be needed for these details and this file should be separate inside the RO-Crate.

**Comment by elichad** [comment]
We made the knowledge graph into an RO-Crate, so this is done
