### ISSUE TITLE
Write 2-page "Why RO-Crate in HDR" motivation

### ISSUE THREAD

**Issue by douglowe** [eScienceLab/RO-Crate_Issues#26]
Draft: https://docs.google.com/document/d/1nHqEZx6HAbBdxeY6yvZisuJ653pSoWgy74zuzHvQAcI/edit

Relevant sections to be added to https://docs.google.com/document/d/1VprT_C_P_bulZs4qZmkPxBWpzgzKxITL/edit?rtpof=true

**Comment by stain** [comment]
https://docs.google.com/document/d/1nHqEZx6HAbBdxeY6yvZisuJ653pSoWgy74zuzHvQAcI/edit Now finished, awaiting feedback from Phil.
