### ISSUE TITLE
RO-Crate validator: review known validator implementations

### ISSUE THREAD

**Issue by elichad** [eScienceLab/RO-Crate_Issues#39]
- [x] https://github.com/ResearchObject/ro-crate-validator-py (Python)
  - Python-based rules for most of the essentials from the spec
  - treats the JSON-LD like regular JSON, so can't tap into the full linked data validation potential
- [x] Crate-O modes https://github.com/Language-Research-Technology/ro-crate-modes/tree/main/modes (JS)
  - Summary of existing tools in https://github.com/Language-Research-Technology/ro-crate-modes/blob/main/docs/soss-profiles.md#tools-for-managing-and-creating-modes-and-sosss (read the rest of the file for an explanation on SOSS/Schema.org Style Schemas)
  - in short: can create a SOSS from an example RO-Crate, which can in turn be used to create a Crate-O mode (written in JSON) _and_ human-friendly documentation
  - can be used for validation, in Crate-O this is done by using the mode as a JSON schema - not clear if there are other tools the SOSS can be plugged in to
  - this looks like a good set of tools especially for new profile developers - would be good to link these to whatever we create
- [x] Describo profile for RO-Crate https://github.com/describo/profiles/blob/master/domain-profiles/ResearchObject-Crate/ro-crate-profile-spec-version-1.1.json
  - Describo profiles documented here https://describo.github.io/docs/profiles/introduction.html#sharing-your-profile
  - seems fairly specific to the Describo infrastructure, not sure it's worth pursuing for use outside Describo
- [x] https://github.com/KockataEPich/CheckMyCrate (Python)
  - also reduces the JSON-LD to JSON for validation
- [x] https://github.com/ResearchObject/ro-crate-validator (C#)
  - also reduces the JSON-LD to JSON for validation
- [x] https://github.com/Sydney-Informatics-Hub/ro-crate-validate
  - not fully implemented - only checks root entity exists & has name/description
- [x] https://github.com/crs4/rocrate-validator/ (Python & SHACL)
  - aligns best with our intent and aims
  - development team at CRS4 are interested in adding LinkML support - see https://github.com/crs4/rocrate-validator/issues/2

**Comment by ianhinder** [comment]
This will be the main focus for Sprint 4.

**Comment by elichad** [comment]
Done; added notes in the original comment
