### ISSUE TITLE
RO-Crate validator: define architecture and tasks

### ISSUE THREAD

**Issue by elichad** [eScienceLab/RO-Crate_Issues#43]
- [x] meet with other validator developers to see if we can agree on a collaborative way forward
- [ ] decide on architecture and key requirements
- [ ] set out initial tasks to build MVP / convert requirements into user stories

First draft of requirements (Oliver and Ian):

- There should be a schema for a general RO-Crate
- Be able to validate an RO-Crate against a schema
- There should be schemas for workflow run RO-Crates
- Should be useable from automated testing
- There should be a defined CLI
- Packaged for PyPI
- People should be able to drop in new profiles and new checks easily
- Should support different levels of validation failure (e.g. error, warning, etc)
- Should work offline
- It should be a python package with a python API

**Comment by stain** [comment]
@OliverWoolland and Eli discussing this week.

**Comment by OliverWoolland** [comment]
Possibly suspended while investigating https://github.com/crs4/rocrate-validator

**Comment by elichad** [comment]
We will move forward with extending https://github.com/crs4/rocrate-validator, as it meets many of the requirements above already and the developers are open to contributions.

I've started set out some initial tasks in the [eScienceLab fork](https://github.com/eScienceLab/rocrate-validator/issues) which @OliverWoolland and I discussed with the package developers.

@alexhambley and @douglowe to consider Cratey requirements and add any further tasks/user stories that will be needed to meet them

**Comment by ianhinder** [comment]
@alexhambley to create a new issue and migrate anything across.
