### ISSUE TITLE
Investigate graph visuallisation

### ISSUE THREAD

**Issue by OliverWoolland** [eScienceLab/RO-Crate_Issues#60]
I've previously used https://sketch.zazuko.com/ for small scale linked data / RO-Crate vis but it is a bit limited.

I was curious about https://github.com/zazuko/blueprint which appears to be a way for exploring layered graphs in a more contextual way

**Comment by stain** [comment]
Could also be made into a tutorial with RO-Crate

**Comment by OliverWoolland** [comment]
https://github.com/zazuko/blueprint/issues/21 my adventures in blueprint are documented here

**Comment by ianhinder** [comment]
Blueprint is the best implementation of KGs, and Oliver is happy he can use it. It doesn't render well, but this is normal and there is nothing better.
