### ISSUE TITLE
Develop docker compose configuration for Cratey

### ISSUE THREAD

**Issue by ianhinder** [eScienceLab/RO-Crate_Issues#73]
Develop docker compose configuration for Cratey

- [ ] Learn docker compose
- [ ] Choose services for Cratey project (db, filestore, api, auth, webserver)
- [ ] Write service definitions
- [ ] Test setup
- [ ] PR
- [ ] Profit!

**Comment by ianhinder** [comment]
Bump to next sprint as Doug is away.

**Comment by alexhambley** [comment]
Closed by https://github.com/orgs/eScienceLab/projects/5/views/2?pane=issue&itemId=86769272&issue=eScienceLab%7CCratey-Validator%7C9
