### ISSUE TITLE
Gather thoughts on knowledge graph plans

### ISSUE THREAD

**Issue by ianhinder** [eScienceLab/RO-Crate_Issues#85]

**Comment by ianhinder** [comment]
Oliver has evaluated https://seco.cs.aalto.fi/tools/sampo-ui/.

**Comment by stain** [comment]
Sampo is actively developed and used (in academia). Compare to Blueprint it may not be as visually pleasing, but could be better to rely on. Oliver considering making views in Sampo to explore workflow runs.  Views have to be defined for each "profile" you want to visualise. To be exploring if this can be used with WorkflowHub knowledge graph.. 

Sampo is a bit less "explory" than Blueprint.
