### ISSUE TITLE
Support BGE team with incorporating RO-Crate into workflows

### ISSUE THREAD

**Issue by ianhinder** [eScienceLab/RO-Crate_Issues#90]
Project board: https://github.com/orgs/bge-barcoding/projects/2 (private, Eli has access)

Rutger wrote some code but it has been removed - https://github.com/naturalis/barcode_validator/blob/74655108bc1d33296b107aaa1e2b9545b6370cd9/examples/ro-crate-meta.json#L2

They are investigating COPO for ENA uploads, which has RO-Crate built in

Update 11 Sep - wait to hear from Rutger who will work on incorporating RO-Crate creation in to some central packages used in the barcoding pipeline. Possibility for support work to arise fairly urgently

Update 1 Oct - expect to get some work out of BGE All Hands for this

Update 12 Nov 
- expecting BGE WP9 to come to data pillar call on 18 Nov with a solid idea about how they want to represent their metadata. From here we will decide next steps about how we support them.
- will get an update on Rutger's work this week (he was away when I last asked 2 weeks ago)

**Comment by elichad** [comment]
This has spawned #94 which is related and will start in Jan/Feb 2025.

Rutger is also working on incorporating RO-Crate support into the barcoding work, so further tasks might appear, however not much help seems to be needed in the meantime, so I'm going to close this issue.
